### ISSUE TITLE
addListener callback function not called on IE11+

### ISSUE THREAD

**Issue by itadakimas** [router5/router5-listeners#2]
Hi,

I am having an issue on IE11+ with the callback function of the addListener method. It's called only once, during the init. If the route changes, it's not called again. No error logged in the console.

It works perfectly on Chrome / Safari / Firefox though.

FYI, I am also using babel-polyfill in my project.

Any idea ?

Thanks !

**Comment by troch** [comment]
Do you use Promises and do you polyfill them for IE? That the only thing I can think of right now.

**Comment by troch** [comment]
Do you have more info / a bit of code to help me replicate?

**Comment by itadakimas** [comment]
Yes, I use Promises and I polyfill them using babel polyfills. I'll give you a bit of code as soon as I can.

**Comment by troch** [comment]
Repo is being deprecated, code has been moved to router5 main repo. Closing this.
