### ISSUE TITLE
Revoked listeners can still get invoked

### ISSUE THREAD

**Issue by jwoudenberg** [router5/router5-listeners#4]
#### The problem in short
Listeners that are being invoked can, among other things, remove other listeners. These removed listeners might then still be invoked in the current 'invocation round'.

#### The use case
I noticed this while working with `react-router5`. Upon navigating away from a page the route listener for the `routeNode` will unmount a component and all its child components. These child components can have their own listeners registered. Those listeners will be removed due to their `componentWillUnmount` hooks. However, because those listeners are already in the `listeners` array that's currently being looped over, they will still be called. Those listeners might attempt to call `setState()` at which point React logs a warning.

#### Possible solution
A solution would be to check that a listener is still in registered right before calling it. I'll have a PR ready in a moment.

**Comment by troch** [comment]
See PR
